### DISCUSSION TITLE
Reset of HA when executing automation

### DISCUSSION THREAD

**Discussion by Buck1976** [do-gooder/rctpower_writesupport#7] [General]
Hi, 

I just implemented the libraries to control my RCT master device (I have 2 inverters, one of them (10) is also connected to Power Battery). Functions like "power_mng.soc_max" are working fine, I can change the values. But when execute this automation (soc_strategy), HA will be rebooted and nothing is changed on RCT: 

`alias: Batterie RCT Setze SOC Maximum
description: Setzt den maximalen Speicherwert der Batterie über ein Python-Skript
trigger:
  - platform: state
    entity_id: input_number.rtc_soc_strategy
    for:
      hours: 0
      minutes: 0
      seconds: 3
condition: []
action:
  - data:
      action: set
      parameter: power_mng.soc_strategy
      value: 2
      host: 10.1.91.170
    action: pyscript.rct_ha_call
mode: single
`
My RCT inverters have version 2.3.5676 and BMS is on 5607.
I tried to execute soc_strategy in many ways, but always without success. Is there maybe a problem with that (ENUM) parameter / variable since new versions? 

Thanks and best regards.

**Comment by heikone** [comment]
Hi,
I can remember that I observed something comparable ... but not sure.
I see, you try to set power_mng.soc_strategy to 2, which means "external".
My system also refused to do that, until @do-gooder provides this [comment](https://github.com/do-gooder/rctpower_writesupport/issues/5#issuecomment-2298209414) to #5.
Maybe this helps?

Setting SOC by the following example runs?
```
alias: Batterie RCT setze SOC Maximum
description: Setzt den den maximalen Speicherwert der Batterie über ein Python-Skript
trigger:
  - platform: state
    entity_id:
      - input_number.rtc_soc_maximum
    for:
      hours: 0
      minutes: 0
      seconds: 3
condition: []
action:
  - service: pyscript.rct_ha_call
    data:
      value: "{{states('input_number.rtc_soc_maximum')|multiply(0.01)|round(2)}}"
mode: single
```
