### DISCUSSION TITLE
Experience with this project

### DISCUSSION THREAD

**Discussion by do-gooder** [do-gooder/rctpower_writesupport#8] [General]
Please describe what you use this project for, how you use it and what you are missing

**Comment by do-gooder** [comment]
I use this project to adjust the emergency power reserve. I also want to use the battery during the dark season to charge the battery when Tibber prices are low.

But I'm still missing the right automation for both. Does anyone have any ideas on how to implement this?

**Comment by maximilianadolf** [comment]
Thank you @do-gooder for the project!

**What is my general environment:**

- Solar power with 6.9 kW Peak
- RCT Power Storage DC 8.0
- RCT Power Battery Master with 5.7 kWh
- Vestel EVC 04 Wallbox
- KIA e-Niro with 64 kWh (11 kW charger)
- Tibber with Tibber Pulse

**My smart home is HomeAssistant on a Raspberry Pi 5.**

**What I use the project for:**

- Prevent usage of battery, when EVCC starts smart charging during nighttime
- Charge battery for daily usage when Tibber prices over the day meet certain criteria

**How did I do that in Homeassitant:**

1. RCT Integration (HACS, https://github.com/weltenwort/home-assistant-rct-power-integration)
2. RCT Power Writesupport (Home Assistant Integration as package (Alternative 2)), to control my RCT
3. EVCC addon (offical addon, https://github.com/evcc-io/hassio-addon)
4. evcc☀️🚘- Solar Charging (https://github.com/marq24/ha-evcc), for usage of entities
5. Tibber Integration (offical integration), for usage of entities
6. Forecast.Solar (offical integration)

**Generated helpers:**

Numeric Input:
input_number.batterieladen_threshold
0.00 € to 0.05 €, giving a threshold value above the minimum day price

Sensor:
sensor.strompreis_tagesminium
`{{ float(state_attr('sensor.your_strompreis', 'min_price')) + float(states('input_number.batterieladen_threshold'))}}`

Reading the daily smallest price, adding the threshold, value is used to get the price for which I want to charge my battery

sensor.strompreis_differenz_max_min
`{{ state_attr('sensor.your_strompreis', 'max_price') - state_attr('sensor.your_strompreis', 'min_price') }}`

Reading the delta between max and min price, value is used to decide, if I want to charge my battery from the grid or if the difference is not big enough to outreach the efficency of charging/discharging my battery

**Automations:**
1. Automation to prevent discharge, when EVCC starts smart charging (I want to keep the generated solar energy in my battery for the next day, when prices will be above my smart charging price from Tibber):
```
alias: Smartes Netzladen - Entladesperre
description: Wenn EVCC Smartes Netzladen startet, dann wird die RCT Batterie gesperrt.
triggers:
  - trigger: state
    entity_id:
      - sensor.evcc_garage_charged_energy
conditions: []
actions:
  - if:
      - condition: state
        entity_id: binary_sensor.evcc_garage_smart_cost_active
        state: "on"
      - condition: state
        entity_id: binary_sensor.evcc_garage_charging
        state: "on"
    then:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: switch.rct_lock_battery
    else:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: switch.rct_lock_battery
mode: single
```
2. Automation to charge my battery when the difference max to min is bigger then 0.109 € (will make that a numeric input as well). 
I check every first minute of the hour, if we are expecting an energy production  of at least 10 kWh from Forecast.Solar (today's forecast before noon, tomorrow's forecast after noon). If this is true, I check if my battery is below 80% SOC, my sensor sensor.strompreis_differenz_max_min is above my target, and the current price within this hour is below my threshold price (min price + threshold). If this is all true, I start charging my battery with switching  switch.rct_max_charge and switch.rct_use_grid_power to ON.
Otherwise, I switch those to off.
```
alias: Batterie Netzladen
description: Lädt die Batterie aus dem Netz zum günstigsten Preis auf.
triggers:
  - trigger: time_pattern
    minutes: "1"
conditions:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: time
            after: "12:00:00"
          - condition: numeric_state
            entity_id: sensor.energy_production_tomorrow
            below: 10
      - condition: and
        conditions:
          - condition: time
            before: "12:00:00"
          - condition: numeric_state
            entity_id: sensor.energy_production_today
            below: 10
actions:
  - if:
      - condition: numeric_state
        entity_id: sensor.strompreis_differenz_max_min
        above: 0.109
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.rct_power_storage_battery_state_of_charge
            below: 80
      - condition: and
        conditions:
          - condition: numeric_state
            entity_id: sensor.your_strompreis
            below: sensor.strompreis_tagesminimum
    then:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.rct_max_charge
            - switch.rct_use_grid_power
    else:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - switch.rct_max_charge
            - switch.rct_use_grid_power
mode: single
```

3. I have another automation, to switch off my charging, when my battery is charged to 80% SOC (need to make that an numeric input as well). It should be triggered, whenever the battery power is changing:
```
alias: Ladebegrenzung Batterie Netzladen
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.rct_power_storage_battery_power
conditions:
  - condition: numeric_state
    entity_id: sensor.rct_power_storage_battery_state_of_charge
    above: 80
actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
        - switch.rct_max_charge
        - switch.rct_use_grid_power
mode: single

```

**Current problems:**
So far I have one problem when I'm smart charging and also want to charge my battery. I think the battery lock also writes a zero to battery_power_extern and hence preventing/overwriting the battery_power_extern to rct_quickcharge_power *-1.
I'll need to see, if I need another switch for writing to RCT, combining those.

Thank you @do-gooder for that wonderful tool so far!
